### ISSUE TITLE
Bug  : invalid syntax in cli.py

### ISSUE THREAD

**Issue by sbert** [fmartingr/pyluxafor#6]
Hi,

When I install I've a non blocking error : 
```
byte-compiling build/bdist.linux-x86_64/egg/luxafor/cli.py to cli.pyc
  File "build/bdist.linux-x86_64/egg/luxafor/cli.py", line 22
    def convert_hex_to_dec_color(hex_color: str) -> tuple:
                                          ^
SyntaxError: invalid syntax
```
Idem When I run the script : 

Traceback (most recent call last):
```
  File "/usr/local/bin/luxa", line 9, in <module>
    load_entry_point('luxafor==0.1.0', 'console_scripts', 'luxa')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 568, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2720, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2380, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2386, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/luxafor-0.1.0-py2.7.egg/luxafor/cli.py", line 22
    def convert_hex_to_dec_color(hex_color: str) -> tuple:
```

**Comment by fatso83** [comment]
I am no Python expert, but whenever you see "SyntaxError" in any language you can assume you are running a too old version of something. Looking at the stack error, I see `.../python2.7`. That doesn't seem very compatible with the installation line:
```
python3 setup.py install
```

This bug should basically be closed, as the installation instructions haven't been followed.

**Comment by fmartingr** [comment]
Ooooops, sorry guys but I totally missed this issue, shouldn't I be automatically watching all my repositories?

As @fatso83 said, this library is Python3 only.

If you're still interested in this I could change the code to make it python2 compatible, but I think it's time to move on ;)
